In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [12]:
X=df.drop('species',axis=1)
Y=df['species']

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33,random_state=42)

In [58]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.transform(X_test)

In [59]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=15)

In [60]:
from sklearn.model_selection import GridSearchCV
classifier=GridSearchCV((model),{
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
},cv=5,scoring='accuracy')

In [61]:
classifier.fit(X_train_scaled,Y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=15),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [62]:
print("Best KNN Parameters:")
print(classifier.best_params_)

print("Best CV Score:")
print(classifier.best_score_)

Best KNN Parameters:
{'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'}
Best CV Score:
0.9400000000000001

In [63]:
best_knn = classifier.best_estimator_

In [64]:
y_pred_knn = best_knn.predict(X_test_scaled)

In [66]:
from sklearn.metrics import accuracy_score
knn_accuracy = accuracy_score(Y_test, y_pred_knn)

print("KNN Test Accuracy:")
print(knn_accuracy)

KNN Test Accuracy:
0.98

In [69]:
results = pd.DataFrame(classifier.cv_results_)

In [70]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001688,0.000532,0.003254,0.001312,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2
1,0.001256,0.000160,0.001960,0.000214,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2
2,0.001170,0.000036,0.002433,0.000073,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.90,0.90,0.9,1.0,0.90,0.92,0.040000,11
3,0.001151,0.000013,0.001863,0.000099,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",1.00,0.85,0.9,1.0,0.95,0.94,0.058310,1
4,0.001404,0.000429,0.002707,0.000535,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.95,0.85,0.9,1.0,0.85,0.91,0.058310,14
5,0.001228,0.000075,0.001935,0.000073,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",1.00,0.85,0.9,1.0,0.90,0.93,0.060000,2
6,0.001239,0.000042,0.002514,0.000084,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",1.00,0.80,0.9,1.0,0.85,0.91,0.080000,14
7,0.001308,0.000216,0.002121,0.000297,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2
8,0.001367,0.000183,0.002612,0.000228,manhattan,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",1.00,0.80,0.9,1.0,0.90,0.92,0.074833,11
9,0.001321,0.000188,0.001937,0.000063,manhattan,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2
10,0.001199,0.000046,0.002658,0.000335,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.95,0.80,0.9,1.0,0.95,0.92,0.067823,13
11,0.001166,0.000028,0.001792,0.000032,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2
12,0.001168,0.000052,0.002373,0.000053,manhattan,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.95,0.85,0.9,1.0,0.95,0.93,0.050990,10
13,0.001151,0.000048,0.001772,0.000017,manhattan,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2
14,0.001148,0.000027,0.002543,0.000163,manhattan,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.95,0.80,0.9,1.0,0.90,0.91,0.066332,14
15,0.001541,0.000470,0.002257,0.000540,manhattan,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",1.00,0.80,0.9,1.0,0.95,0.93,0.074833,2

In [72]:
results[["param_metric","param_n_neighbors","param_weights","mean_test_score"]]

   param_metric  param_n_neighbors param_weights  mean_test_score
0     euclidean                  3       uniform             0.93
1     euclidean                  3      distance             0.93
2     euclidean                  5       uniform             0.92
3     euclidean                  5      distance             0.94
4     euclidean                  7       uniform             0.91
5     euclidean                  7      distance             0.93
6     euclidean                  9       uniform             0.91
7     euclidean                  9      distance             0.93
8     manhattan                  3       uniform             0.92
9     manhattan                  3      distance             0.93
10    manhattan                  5       uniform             0.92
11    manhattan                  5      distance             0.93
12    manhattan                  7       uniform             0.93
13    manhattan                  7      distance             0.93
14    manhattan                  9       uniform             0.91
15    manhattan                  9      distance             0.93